### ISSUE TITLE
Kubernetes Service Importer | No reconnection if watch gets closed

### ISSUE THREAD

**Issue by reste85** [vert-x3/vertx-service-discovery#113]
We've a problem watching the kubernetes api using KubernetesServiceDiscoveryImporter provided in the vertx-servicediscovery distribution. More specifically it seems that, if for some reason the watch gets disconnected, it doesn't reconnect anymore to the kubernetes /services endpoint.
We're experiencing that in our kubernetes cluster, and for what i'm seeing in the code, the case of disconnection isn't managed. Am i missing something?

PS: we're using vert.x 3.6.2, but also in the 3.8.1 code the reconnection isn't managed.

**Comment by vietj** [comment]
@cescoffier does it ring a bell ?

**Comment by reste85** [comment]
Any updates on this?

**Comment by vietj** [comment]
unfortunately we haven't done progress on this

**Comment by reste85** [comment]
> are you interested in contributing this @reste85 ?

I've wrote you on gitter some times ago, it could be feasible in my spare time to do that, but i need some advices about that
