### ISSUE TITLE
RedisBackendService seems no way to close redis client

### ISSUE THREAD

**Issue by nousxiong** [vert-x3/vertx-service-discovery#117]
### Questions

RedisBackendService seems no way to close its own redis client.

I read ServiceDiscovery.close code(which DiscoveryImpl.close), found out there is no code to call backend close or shutdown or some method(I know there isn't one), so If I choose RedisBackend,RedisBackendSerivce's member redis(which type is RedisClient) will never be closed?

If this is currect, this redis client 's socket may be leak?

### Version

3.8.3

**Comment by tsegismont** [comment]
You are right.

Nevertheless in most cases a single instance of `ServiceDiscovery` is created for as long as the JVM live so it should not harm too much.

Would you like to contribute a fix ?
