### ISSUE TITLE
vertx-service-discovery-bridge-docker uses a different version of jackson

### ISSUE THREAD

**Issue by paulgallagher75** [vert-x3/vertx-service-discovery#132]
the pom.xml for vertx-service-discovery-bridge-docker defines its own property **_<jackson.version>2.9.9</jackson.version>_** which will override the one set in vertx-dependencies _**<jackson.version>2.11.3</jackson.version>**_ (which is imported in the parent) which every module of vertx uses, should we not remove the property to standardise on the vertx-dependencies version

I don't know the original disicion on this or if it was just overlooked but 2.9.9 is very old now and many CVE's have been fixed since then

**Comment by tsegismont** [comment]
Closed in
