### ISSUE TITLE
Metadata always overwrite when type is set

### ISSUE THREAD

**Issue by adhesivee** [vert-x3/vertx-service-discovery#139]
### Version

4.0.2

### Context

When creating a record with [MessageSource#createRecord](https://github.com/vert-x3/vertx-service-discovery/blob/4.0.2/vertx-service-discovery/src/main/java/io/vertx/servicediscovery/types/MessageSource.java#L53) always overwrite metadata if [type is not null](https://github.com/vert-x3/vertx-service-discovery/blob/4.0.2/vertx-service-discovery/src/main/java/io/vertx/servicediscovery/types/MessageSource.java#L65)

Documentation is not mentioning anything about this. So I would assume this is a bug.

**Comment by tsegismont** [comment]
@adhesivee right, this is a bug
