### ISSUE TITLE
Record lookup very slow when a lot of records are published

### ISSUE THREAD

**Issue by robertonav20** [vert-x3/vertx-service-discovery#144]
### Version

Version: 3.9.3

### Context

The production environment contain 3000 verticle approx. When i use the method getRecord/getRecords for to get the current status of a verticle result to much slow.
The reason of this problem is because the methods get all data, stored in memory and then apply the filter function.

### Steps to reproduce

1. Create a instance of vertx
2. Create a Service Discovery instance
3. Deploy 2000/3000 verticles
4. Try to measure getRecord/getRecords response time and compare with the response time of the same methods from a smaller enviroment (50 verticles deployed)

### Extra
I suggest a more efficient store method which use a unique key passed by the user or record.getRegistration(), against UUID.randomUUID().toString(), because with UUID key the user cannot read the record instantly and the service discovery must to get all data and apply function filter after read all 2k-3k etc.....

JVM version : OpenJDK 1.8.191

**Comment by tsegismont** [comment]
@robertonav20 can you share a pull request?

**Comment by robertonav20** [comment]
Hi,
you can see the pr here https://github.com/vert-x3/vertx-service-discovery/pull/145
