### ISSUE TITLE
Fix artifact id naming

### ISSUE THREAD

**Issue by vietj** [vert-x3/vertx-service-discovery#16]
Currently the poms are named:

- vertx-microservice-toolbox (parent)
- vertx-circuit-breaker
- vertx-discovery-service
- vertx-discovery-bridge-kubernetes

the artifact should begin by the same proxy for instance:

- vertx-microservices-toolbox-parent (parent)
- vertx-microservices-toolbox-circuit-breaker (parent)
- vertx-microservices-toolbox-discovery-service(parent)

etc...

note this example is the simplest that came out of my mind and we may want to have something shorter

**Comment by cescoffier** [comment]
Kind of long but can't find an obvious shorted one

**Comment by cescoffier** [comment]
Actually, maybe the idea to put everything in one project has limits. Typically, the circuit breaker may be in a separate project, as even it is became popular with microservices, it's not limited to this type of architecture.

Same things with the discovery. Then, in one of these project, common prefixes make sense.

**Comment by cescoffier** [comment]
Done by splitting the project.
