### ISSUE TITLE
ClassLoaderUtils do not try all available class loaders

### ISSUE THREAD

**Issue by daveekr** [vert-x3/vertx-service-discovery#173]
### Version

4.x

### Context

If you try to get a service object via `io.vertx.servicediscovery.ServiceReference#get` method, this calls the `io.vertx.servicediscovery.utils.ClassLoaderUtils#load` method which does not resolve all available class loaders, which causes some classes to not be found.

### Do you have a reproducer?

No, but here is why: 

https://github.com/vert-x3/vertx-service-discovery/blob/50a8e81ecd25bd50601fd5233e6b722b1e50da75/vertx-service-discovery/src/main/java/io/vertx/servicediscovery/utils/ClassLoaderUtils.java#L33-L50 
In line 41 the result of `tryLoad()` is directly returned instead of assigned to `loaded`

### Steps to reproduce

Happened to me, when using Quarkus 3.2.10.Final with Vert.x Service Discovery in a multi-module Maven project.
1. Create service interface in module x
2. Create eventbus service implementing 1) in module y
3. Publish eventbus service in module y
4. Try to use interface from module z (Quarkus)

### Extra

Java 11.0.22 Azul

I am going to provide a fix and create a PR for this issue.

**Comment by tsegismont** [comment]
Fixed in a13d9c9b
