### ISSUE TITLE
Bridges interact with BridgeImporter / BridgeExporter instead of ServiceDiscovery

### ISSUE THREAD

**Issue by vietj** [vert-x3/vertx-service-discovery#20]
The discovery service combines at two features:

- discovery services
- distribute these discovered services and allow to query/filter them

Extract the discovery logic in a client so it can be used without the service.

**Comment by cescoffier** [comment]
You mean extracting a lookup interface and publisher interface ? 

Most of the service-based system don't do this distinction.

**Comment by vietj** [comment]
I mean a way to make discovery of such clients without the service and the replication.

for example:

```
// Just discovert thing, don't start a service just to be aware of what service can be found
DiscoveryClient client = createClient(config);
client.performDiscovery(results -> {
  // Get what has been discovered
});
```

**Comment by cescoffier** [comment]
I still don't get it, when you have your instance of DiscoveryService, you don't do the lookup right away, you do your lookup when you call getRecords. The only benefits there is the "config". 

Actually it's close to what we called service locator:

```
locator = ServiceLocator.create(discovery, filter);
locator.locate(result -> {
});
```

However, I've dropped this idea, maybe we should consider it again.

**Comment by vietj** [comment]
this idea is about making the discovery in a client, so it can be controlled by the code that uses the client.

the service discovery will use this client, i.e periodically it will call the client to refresh its data and republish things in the distributed and emits events on the bus.

for other needs I just need a simple client for discovery, I don't need a shared data structure + event bus.

**Comment by vietj** [comment]
basically the client idea is very simple, you create a client and call it. This client wraps the DockerClient, etc... nothing more. So it is more or less a trivial refactoring of the current existing code.

**Comment by cescoffier** [comment]
I'm still confused.

Do you mean for bridges ? Instead of using a bridge, it would use a "client" ?
If this is the case, bridges are a bit more complicated than raw clients as it should detect leaving services and update the discovery service, while a client would just locate the service. So, I don't think it's a refactoring, it's a new feature, having "discovery client" that act as simple locator for a specific discovery mechanism.

If you need a client without the shared data structure + event bus, you can just have your own discovery backend that is just a map (it's actually the fallback when vert.x is not in cluster mode). However, it would only get the services directly registered on it (either explicitly or by bridges registered on this discovery service instance).

**Comment by vietj** [comment]
when I was looking at the code, I only looked at the docker client implementation that manages itself the removed container so I thought it was a general mechanism, but the K8S bridge uses the watch service of the K8S api. So it means indeed that the bridge manage the life cycle (i.e it watches) and cannot be a pure client.

So yes it would be more or less the ability to run bridges without the discovery service.

So we could see that as having the bridges publishing in a subset of the DiscoveryService that only does the publish/unpublish part and not the rest.

**Comment by cescoffier** [comment]
I think we can improve the bridge API to be much easier to implement and avoid duplication.

There are 3 types of discovery (the type depends on the underlying discovery infrastructure):

* static discovery - a bridge implementing such kind of discovery that would publish a set of services in its `start` method and unpublish it in the `stop` method. Implementations would have a single method: `List<Record> get()`;
* periodic discovery - a bridge that periodically scans _something_ and adapts the set of record based on the scan result. Implementations would have a single method: `List<Record> get()` that it periodically called. The caller (that need to be determined) would keep track of the returned records to unpublish the ones that are gone, publish the new ones... On `stop` all imported services are withdrawn.
* dynamic discovery - a bridge using a _listener_ ability of the discovery technology that notify it when services are published or withdrawn.

**Comment by vietj** [comment]
my point is to decouple the bridge from the ServiceDiscovery interface that provides several concerns and only keep part used by the bridge which is publish/unpublish.

**Comment by cescoffier** [comment]
oh you mean not registering the bridge on the discovery service but initialize the bridge with a discovery service instance ?

Instead of:

```
DiscoveryService.create().registerBridge(....);
```

Doing something like:

```
DiscoveryService svc = ....
ConsulBridge bridge = ConsulBridge.create(svc, conf);
```

right now it's made like that because there is a link between the discovery service lifecycle and bridge lifecycle.

**Comment by vietj** [comment]
the second but you replace DiscoveryService by :

```
interface BrideListener {
   void publish();
   void unpublish();
}
```

and then the DiscoveryService expose an impl of BridgeListener to its managed bridges

**Comment by cescoffier** [comment]
That's just for importer bridge. Bridges are bi-directional (even if the second direction has not been implemented in any of the bridge for now).

**Comment by vietj** [comment]
oh right I see, can we split that in two interfaces that and the bridge that export use this other interface ?

so BridgeImporter / BridgeExporter

**Comment by cescoffier** [comment]
+1

**Comment by cescoffier** [comment]
Has been fixed by @vietj 

closing this issue.
