### ISSUE TITLE
Allow endpoint discovery by namespace

### ISSUE THREAD

**Issue by amoAHCP** [vert-x3/vertx-service-discovery#24]
You currently resolve the endpoints by using the namespace and the label (client.endpoints().inNamespace(namespace).withLabel(label, labelValue).list();) which is fine. In some situations you may want to get all pods in one namespace. The reason for this may be: you have a vertx cluster running and providing different service endpoints to access the cluster (customerService, ProductService). In this case you don't want to bind your pods to a single label or service.

**Comment by cescoffier** [comment]
Hi @amoAHCP - can be considered this issue fixed ?

**Comment by amoAHCP** [comment]
Hi, yes ... but not before monday. 

Andy

**Comment by cescoffier** [comment]
I can close it, thanks !
