### ISSUE TITLE
Allow filtering on 'type' in Record.match()

### ISSUE THREAD

**Issue by aschrijver** [vert-x3/vertx-service-discovery#33]
Is there a reason why 'type' is not supported in record filtering?
I would like to be able to filter on all Record properties, including 'type'.

https://github.com/vert-x3/vertx-service-discovery/blob/master/vertx-service-discovery/src/main/java/io/vertx/servicediscovery/Record.java#L211

**Comment by cescoffier** [comment]
There is one reason.... I forgot ;-)

It should be added.

**Comment by aschrijver** [comment]
Great, thanks!
