### ISSUE TITLE
Expose ServiceDiscoveryOptions used on started ServiceDiscovery instances

### ISSUE THREAD

**Issue by aschrijver** [vert-x3/vertx-service-discovery#34]
Consuming and `announce` and `usage` events is straightforward when service discovery creation and registration occur in the same object, but when passing the discovery instance around to other objects there is no way to determine on which addresses it is broadcasting events, because the used `ServiceDiscoveryOptions` is not exposed on the discovery instance.

True, you can externalize the addresses to known values, but this becomes unwieldy when having multiple service discovery instances.
Therefore I would like to have the deployed options exposed on the service discovery instance.

**Comment by cescoffier** [comment]
👍 

It would be a nice improvement. Fancy a PR ?

**Comment by cescoffier** [comment]
I was on this project, so did it.

**Comment by aschrijver** [comment]
Thanks! I didn't see your pull request request. Sorry :)
I am about to release an extension of the service discovery with a new `graphql-service` type (maybe tomorrow or the day after).
The project will be here: https://github.com/engagingspaces/vertx-graphql-service-discovery

**Comment by cescoffier** [comment]
Can't wait, it looks pretty cool!

**Comment by aschrijver** [comment]
Well, the code is there now. Still have to create some README lines, and more fun like that :)
