### ISSUE TITLE
Consul services can have several providers

### ISSUE THREAD

**Issue by edgar615** [vert-x3/vertx-service-discovery#39]
I has 2 db instance
 `curl http://10.4.7.220:8500/v1/catalog/service/db`

> [
> {"Node":"ubuntu221","Address":"10.4.7.221","ServiceID":"ubuntu221:mysql:3306","ServiceName":"db","ServiceTags":["master","backups"],"ServiceAddress":"","ServicePort":32769},{"Node":"ubuntu220","Address":"10.4.7.220","ServiceID":"ubuntu220:mysql:3306","ServiceName":"db","ServiceTags":["master","backups"],"ServiceAddress":"","ServicePort":32771}
> ]

When I use 
`discovery.getRecords(r -> true, ..)` ，only get the first data

```
private String importService(JsonArray array, Future<Void> future) {
    if (array.isEmpty()) {
      Future.failedFuture("no service with the given name");
      return null;
    } else {
      JsonObject jsonObject = array.getJsonObject(0);
      String address = jsonObject.getString("Address");
      String name = jsonObject.getString("ServiceName");
      String id = jsonObject.getString("ServiceID");
	}
	...
}
```	

I'm sorry my English is not good

**Comment by cescoffier** [comment]
You are right. I should import all. 

the mapping between vert.x services and consul services is not 1-1 in this case.

**Comment by cescoffier** [comment]
I've renamed the issue to be more explicit
