### ISSUE TITLE
Record retrieval with ConsulServiceDiscovery may be incorrect

### ISSUE THREAD

**Issue by edcaceres** [vert-x3/vertx-service-discovery#43]
Once i retrieve a service reference trough ConsulServiceDiscovery, i'm getting:

Vertx record:
<img width="1224" alt="screen shot 2016-09-27 at 5 47 20 pm" src="https://cloud.githubusercontent.com/assets/782909/18893858/a7d93ab8-84dd-11e6-8ddb-71ac2c928a8b.png">

Consul Service:
<img width="513" alt="screen shot 2016-09-27 at 6 14 01 pm" src="https://cloud.githubusercontent.com/assets/782909/18894358/7445d190-84e0-11e6-9cce-e2bf990fe223.png">

i think the location.host should be the ServiceAdress and not the Consul node Address... 

Im using vertx 3.3.3

**Comment by edcaceres** [comment]
Now i understand the problem. 

Currently vertx assume that in the service definition "Node.Address" is always pointing to the service address but this seems only correct when the service is in a container holding a consul agent, if the service container does not have a consul agent, the service definition "Node.Adress" will contain the consul server address.

**Comment by faferreyra** [comment]
Found the same problem. I think it's wrong to use the Node.Address value, as it advertises the Consul agent that registered the service.

I would push a PR with my "opinionated" fix, but it's open to discussion.

**Comment by cescoffier** [comment]
Should be fixed by #62
