### ISSUE TITLE
Rewrite the consul importer using the vertx-consul-client

### ISSUE THREAD

**Issue by cescoffier** [vert-x3/vertx-service-discovery#53]

**Comment by Cafeinoman** [comment]
Can't we use vertx-consul-client to add a ServiceExporter? Or even a full ServiceDiscoveryBackend?

**Comment by cescoffier** [comment]
Yes, all three extensions can be provided using the vertx-consul-client.

**Comment by Cafeinoman** [comment]
Nothing to do this week-end, I take it...

**Comment by ruslansennov** [comment]
@Cafeinoman I believe this should be done with blocking queries (see [hashicorp implementation](https://github.com/hashicorp/consul/tree/master/watch)). Watches as a part of `vertx-consul-client` module will be ready within few days

**Comment by cescoffier** [comment]
Done as part of #62
