### ISSUE TITLE
Update docs on website

### ISSUE THREAD

**Issue by kerko** [vert-x3/vertx-service-discovery#57]
It seems like the docs at http://vertx.io/docs/vertx-service-discovery/java/#_implementing_your_own_service_type are not uptodate with the information in this repo.
Especcialy the part about implementing your own service says on the website:
> Create a `META-INF/services/io.vertx.ext.discovery.spi.ServiceType`

But the correct way this File should be named, since the classpath changed is:
> Create a `META-INF/services/io.vertx.servicediscovery.spi.ServiceType` file

Also wrong : 
> Create a class extending `io.vertx.ext.discovery.types.AbstractServiceReference`

Since the loading of your own spi fails silently if you just copy pasted the filename, the docs should probably be updated.
I did not check if other parts of the docs are outdated, maybe?

**Comment by cescoffier** [comment]
Hi, The website is updated during the release process. So it will be fixed when we will release 3.4.0 (G.A.). I'm going to push the documentation for the 3.4.0.Beta1 Today with the fix.

**Comment by cescoffier** [comment]
3.4.0 has been released.
