### ISSUE TITLE
RxJava ServiceReference.get() doesn't support io.vertx.rxjava.core.http.HttpClient

### ISSUE THREAD

**Issue by chefhoobajoob** [vert-x3/vertx-service-discovery#58]
When using classes from `io.vertx.rxjava.servicediscovery`, and using references to retrieve `HttpClient` instances, the `ServiceReference` class will not produce rxjava `HttpClient` service objects.

Attempting to get instances of `io.vertx.rxjava.core.http.HttpClient` produces an exception:
```
java.lang.ClassCastException: io.vertx.core.http.impl.HttpClientImpl cannot be cast to io.vertx.rxjava.core.http.HttpClient
```

The RxJava `ServiceReference` class should support the ability to retrieve RxJava `HttpClient` service objects.

**Comment by cescoffier** [comment]
Did you try 3.4.0.Beta1 ? 

This issue has been fixed in this version. 

In addition, I would recommend using the new web client, with:

```
Single<WebClient> single = HttpEndpoint.rxGetWebClient(discovery, rec -> rec.getName().equals("my-service-name"));
```

**Comment by chefhoobajoob** [comment]
I hadn't seen the beta - will give this a try. Thanks!

**Comment by cescoffier** [comment]
@chefhoobajoob did you had time to test ?

**Comment by chefhoobajoob** [comment]
I haven't yet, but did review the release notes and doc preview. Might be a week or so before I can actually give it a run. Thank you for the reference!

**Comment by cescoffier** [comment]
3.4.0 has been released.

**Comment by chefhoobajoob** [comment]
@cescoffier: well, here's how backlogged we've been. We upgraded a few weeks back, and I'm just now able to take a look at the rx api for the new WebClient!

You are right - it is a significant improvement on the rx shim over the earlier HttpClient. Kudos to you and the team for the great work.

**Comment by cescoffier** [comment]
That's a great news, thanks for the feeback !
