### ISSUE TITLE
About the Redis Backend: ⚠️ `setBackendConfiguration` and `new ServiceDiscoveryOptions` do not produce the same configuration

### ISSUE THREAD

**Issue by k33g** [vert-x3/vertx-service-discovery#66]
Probably not a 🐞, but it could be useful to put this "subtlety" in the documentation of the Redis Backend (and perhaps the other backends)

This source code produces at the registration a redis `HASH` named `ms.vert.x`:

```java
ServiceDiscoveryOptions serviceDiscoveryOptions = new ServiceDiscoveryOptions();

discovery = ServiceDiscovery.create(
  vertx,
  serviceDiscoveryOptions.setBackendConfiguration(
    new JsonObject()
      .put("host", redisHost)
      .put("port", redisPort)
      .put("auth", redisAuth)
      .put("key", "ms.vert.x")
  ));
```

This source code produces at the registration a redis `HASH` named `records` (the key `key` isn't used):

```java
ServiceDiscoveryOptions serviceDiscoveryOptions = new ServiceDiscoveryOptions();

discovery = ServiceDiscovery.create(
  vertx,
  new ServiceDiscoveryOptions(
    new JsonObject()
      .put("host", redisHost)
      .put("port", redisPort)
      .put("auth", redisAuth)
      .put("key", "ms.vert.x") // not taken into account
  ));
```

**Comment by cescoffier** [comment]
The second snippet does not configure Redis. If the Redis backend is present, it's going to be used using the default configuration. Of course in this case, `key` is not used (as well as host, port and auth).
