### ISSUE TITLE
DiscoveryImpl.publish publishes DOWN and UNKOWN Records as UP

### ISSUE THREAD

**Issue by mnikliborc** [vert-x3/vertx-service-discovery#69]
DiscoveryImpl.publish(Record record, Handler<AsyncResult<Record>> resultHandler) method resets the status of provided Record with following code:

`Status status = record.getStatus() != null
      && record.getStatus() != Status.UNKNOWN
      && record.getStatus() != Status.DOWN
      ? record.getStatus() : Status.UP;`

So when I publish a Record that is DOWN, its status is reset to UP. It seems the return values in the ternary operator should be switched:

`Status status = record.getStatus() != null
      && record.getStatus() != Status.UNKNOWN
      && record.getStatus() != Status.DOWN
      ? Status.UP : record.getStatus();`

This way if the status is DOWN or UNKOWN it is unchanged, all the other statuses are defaulted to UP.

Is it a bug or I'm missing something?

**Comment by cescoffier** [comment]
It's a bug definitely.

**Comment by cescoffier** [comment]
BTW, there is also the `OUT_OF_SERVICE` state indicating that a service is alive, but not in a _good shape_.
