### ISSUE TITLE
ServicePublisher should expose the update(...) method

### ISSUE THREAD

**Issue by gsson** [vert-x3/vertx-service-discovery#72]
I am implementing a `io.vertx.servicediscovery.spi.ServiceImporter`.

The docs for `ServiceImporter.start(...)` says
```  /**
  * Starts the importer.
  *
  * @param vertx         the vertx instance
  * @param publisher     the service discovery instance
  * @param configuration the bridge configuration if any
  * @param future        a future on which the bridge must report the completion of the starting
  */
```

However, the type of `publisher` is not `ServiceDiscovery`, but `ServicePublisher`.

Which is fine, except that `ServicePublisher` doesn't contain the `update(...)` method from `ServiceDiscovery`, and I occasionally see events (metadata changes etc) where I would rather update a `Record` rather than unpublish+publish a new record.

Is the omission of `update(...)` in `ServicePublisher` an oversight, or is there a reason for this omission?

**Comment by cescoffier** [comment]
It's definitely a bug. I will have a look.
