### ISSUE TITLE
Missing RxJava2 version of KubernetesServiceImporter

### ISSUE THREAD

**Issue by codepitbull** [vert-x3/vertx-service-discovery#75]
There is a RxJava2-version of ServiceDiscovery (io.vertx.reactivex.servicediscovery.ServiceDiscovery) but no counterpart of KubernetesServiceImporter.
I gave the others a quick glance and looks like none of the bridges include RxJava2-versions of their classes which renders a RxJava2-ServiceDiscovery useless.

**Comment by cescoffier** [comment]
Why bridges should have a RX Java 2 generation ? It's only used internally by the service discovery

**Comment by codepitbull** [comment]
When using **io.vertx.reactivex.servicediscovery.ServiceDiscovery** one can only provide rxified-versions for the importers:
The following code fails if you try to use a non-rxified ServiceImporter withan rxified-ServiceDiscovery
```
ServiceDiscovery discovery = ServiceDiscovery.create(vertx.getDelegate());
discovery.registerServiceImporter(new KubernetesServiceImporter(), new JsonObject());
```

**Comment by cescoffier** [comment]
Oh, I see... documentation issue ;-) 
The Kubernetes bridge is automatically added if it found it in your classpath. No need to register it explicitly.

**Comment by codepitbull** [comment]
Aaaaah, ok, that solves the issue :)
Should I open a new bug?

**Comment by cescoffier** [comment]
Yes please, about the documentation that is not "as good as it should be" ;-)
