### ISSUE TITLE
Custom ServiceReferences now need to override onClose() for their cleanup to run, but this isn't documented.

### ISSUE THREAD

**Issue by dano** [vert-x3/vertx-service-discovery#77]
[This commit](https://github.com/vert-x3/vertx-service-discovery/commit/f2fe04842679015a30f1acb15e081127088d3726) changed the `AbstractServiceReference` method that is called when releasing a reference from `close()` to `onClose()`. All the built-in service types were updated to reflect this, but it silently broke anyone who wrote a custom `ServiceType`/`ServiceReference` that overrode `close()` to have it's cleanup run (which is explicitly suggested in [the docs](http://vertx.io/docs/vertx-service-discovery/java/#_implementing_your_own_service_type)).

I guess at the very least the docs should be updated to recommend overriding `onClose`, though I'm not sure if the backwards-incompatible change was actually intended, so maybe you might want to take some other action.

**Comment by cescoffier** [comment]
Thanks for reporting this! It was not intended at all. Let me have a look.

**Comment by vietj** [comment]
@cescoffier any progress on this ?

**Comment by cescoffier** [comment]
Not yet, but it's going to be fixed soon
