### ISSUE TITLE
Location metadata not found when use ConsulBackendService as backend

### ISSUE THREAD

**Issue by GaryChengld** [vert-x3/vertx-service-discovery#90]
When use ConsulBackendService as backend SPI based on Consul, the Record returns from ServiceDiscovery doesn't include Location metadata

**Comment by GaryChengld** [comment]
The issue can be fixed once I change code in line 205

`tags.stream().filter(t -> t.startsWith("location:")).map(s -> s.substring("location:".length())).map(JsonObject::new).forEach(json -> json.mergeIn(record.getMetadata()));`

to 

`tags.stream().filter(t -> t.startsWith("location:")).map(s -> s.substring("location:".length())).map(JsonObject::new).forEach(json -> record.getLocation().mergeIn(json));
`

**Comment by cescoffier** [comment]
Sorry for the delay, missed this one. I've applied your fix. Thanks!
